Revert "msm: port memtype header from leanKernel-note3"
This reverts commit 8804bdb585e84e1b86040ed7a622dd4b40bf17a3.

Build failed with:

arch/arm/mach-msm/built-in.o: In function `apq8084_reserve':
:(.init.text+0x1d2c): undefined reference to `msm_reserve'